name: run tests on devnet
on:
  pull_request:
    branches:
      - '**'
    paths:
      - '**'
  push:
    branches:
      - '**'
    paths:
      - '**'

jobs:
  test:
    name: run tests on devnet
    runs-on: ubuntu-latest

    services:
      devnet:
        image: shardlabs/starknet-devnet-rs:0.0.4-seed0
        ports:
          - 5050:5050

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'
      - run: cd smartr_account && npm ci --ignore-scripts
      - run: cd smartr_account && cp .env.template.json .env.devnet.json
      - run: cd smartr_account && npm run test
