name: 0xknwn/starknet-test-helpers tests
on:
  pull_request:
    branches:
      - '**'
    paths:
      - 'sdk/starknet-test-helpers/**'
      - 'src'
  push:
    branches:
      - 'develop'
    paths:
      - '**'

jobs:
  test:
    uses: ./.github/workflows/_sdks_jest.yml
    with:
      workspace: "@0xknwn/starknet-test-helpers"
