name: 0xknwn/starknet-account tests
on: workflow_dispatch
  # pull_request:
  #   branches:
  #     - '**'
  #   paths:
  #     - '**'
  # push:
  #   branches:
  #     - 'develop'
  #   paths:
  #     - '**'

jobs:
  test:
    uses: ./.github/workflows/_sdks_jest.yml
    with:
      workspace: "@0xknwn/starknet-account"
