name: 0xknwn/starknet-account sdk tests
on:
  pull_request:
    branches:
      - '**'
    paths:
      - '**'
      - '!docs/*'
  push:
    branches:
      - 'develop'
    paths:
      - '**'

jobs:
  test:
    uses: .github/workflows/sdk-starknet-account.yml
    with:
      workspace: "@0xknwn/starknet-account"
